name: reusemart_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^17.0.0
  firebase_analytics: ^11.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.19.0
  animate_do: ^3.0.0
  page_transition: ^2.0.9

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logoReUseMart.png
    - lib/assets/pp.png
