// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4AwlL-fbh0ACG0TbuKxuEle0K8Olgc7o',
    appId: '1:657796440182:web:88cba6d4fd1954163ebf57',
    messagingSenderId: '657796440182',
    projectId: 'reusemart-mobile',
    authDomain: 'reusemart-mobile.firebaseapp.com',
    storageBucket: 'reusemart-mobile.firebasestorage.app',
    measurementId: 'G-978F0KK89E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXN-KRtkjwU8zaKTrymIWUB96kPI-SEv8',
    appId: '1:657796440182:android:b9e453e4319390493ebf57',
    messagingSenderId: '657796440182',
    projectId: 'reusemart-mobile',
    storageBucket: 'reusemart-mobile.firebasestorage.app',
  );
}
